name: Kotlin Multiplatform Cache
description: A GitHub Actions workflow for caching a Kotlin Multiplatform project using the Gradle build system.

runs:
  using: composite
  steps:
    - name: Cache Gradle
      uses: actions/cache@v4.1.1
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'buildSrc/**/Versions.kt', 'buildSrc/**/Dependencies.kt', 'gradle/*.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache konan
      uses: actions/cache@v4.1.1
      with:
        path: |
          ~/.konan/caches
          ~/.konan/dependencies
          ~/.konan/kotlin-native-prebuilt-*
        key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'buildSrc/**/Versions.kt', 'buildSrc/**/Dependencies.kt', 'gradle/*.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-konan-
