name: PR job

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.png"
      - docs

jobs:
  pre-conditions:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: corretto
          java-version: 18

      - name: Cache Kotlin Multiplatform
        uses: ./.github/actions/kmp_cache

      - name: detekt
        run: ./gradlew detekt --stacktrace

      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: ./iosApp

  build-android:
    needs: pre-conditions
    runs-on: ubuntu-24.04
    outputs:
      kover_report_available: ${{ steps.kover_report.outputs.kover_report_available }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: corretto
          java-version: 18

      - name: Cache Kotlin Multiplatform
        uses: ./.github/actions/kmp_cache

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Kover XML Report
        uses: ./.github/actions/kover_report
        id: kover_report
        with:
          kover_report_path: ${{ github.workspace }}/composeApp/build/reports/kover/reportDebug.xml
          artifacts_name: android-test-report

      - name: Upload Kover Report
        if: steps.kover_report.outputs.kover_report_available == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.kover_report.outputs.artifacts_name }}
          path: ${{ github.workspace }}/composeApp/build/reports/kover/reportDebug.xml
          retention-days: 5

  build-ios:
    needs: pre-conditions
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: corretto
          java-version: 18

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Kotlin Multiplatform
        uses: ./.github/actions/kmp_cache

      - name: Select Xcode version
        run: |
          XCODE_VERSION="15.0"
          sudo xcode-select -s "/Applications/Xcode_${XCODE_VERSION}.app"

      - name: Build
        run: |
          cd iosApp
          rm -f iosApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
          xcodebuild -resolvePackageDependencies -project iosApp.xcodeproj
          xcodebuild build-for-testing \
            -scheme "iosApp" \
            -project iosApp.xcodeproj \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
            -allowProvisioningUpdates \
            -configuration Debug \
            DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }}

  comment-test-report:
    needs: [build-android]
    if: |
      always() &&
      github.event_name == 'pull_request' &&
      needs.build-android.outputs.kover_report_available == 'true'
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Comment Kover Report to PR
        uses: ./.github/actions/comment_kover_report_to_pr
        with:
          platform: Android
          report_name: android-test-report
